# Generated by Django 5.2 on 2025-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
