# Generated by Django 5.2 on 2025-04-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, upload_to="profile_pic"),
        ),
    ]
